
server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: ${LOG_FILE_PATH:/var/log/service-discovery/prod_log.log}
    clean-history-on-start: ${LOG_CLEAN_HISTORY_ON_START:false}
  level:
    org:
      hibernate:
        SQL: INFO
      springframework:
        web: INFO
        data: INFO
      boot:
        autoconfigure:
          data:
            rest: INFO
            jpa: INFO
            orm: INFO

